version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=docker
      - MONGO_URI=${MONGO_URI_DOCKER}
    depends_on:
      - mongo
    networks:
      - app_network

  mongo:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:4000
    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network:
    driver: bridge
