version: '3.8'

services:
  backend:
    build:
      context: ./backend         
    ports:
      - "4000:4000"  
    environment:
      - NODE_ENV=production  
      - DATABASE_URL=mongodb://mongo:27017/ai_content_management 
      - AI_API_KEY=${AI_API_KEY}  
    depends_on:
      - mongo  

  mongo:
    image: mongo:5  
    ports:
      - "27017:27017" 
    volumes:
      - mongo_data:/data/db  

  frontend:
    build:
      context: ./frontend        
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:4000  

volumes:
  mongo_data:
